spring:
  cloud:
    gateway:
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung*
          filters:
            - RewritePath=/baeldung(?<segment>/?.*), $\{segment}
        - id: catch-all
          uri: http://localhost:8000
          predicates:
            - Path=/api/*
      default-filters:
        - TokenRelay=
        - CustomFilter=
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: f678afd5e716ecb79812
            client-secret: <redacted>
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
management:
  endpoints:
    web:
      exposure:
        include: "*"
