spring:
  cloud:
    gateway:
      routes:
        - id: baeldung_route
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/
        - id: catch-all
          uri: http://localhost:8000
          predicates:
            - Path=/*
      default-filters:
        - TokenRelay=
  security:
    oauth2:
      client:
        provider:
          battle-net:
            issuer-uri: https://oauth.battle.net
        registration:
          battle-net:
            provider: battle-net
            client-id: <redacted>
            client-secret: <redacted>
            scope:
              - openid
              - wow.profile
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
management:
  endpoints:
    web:
      exposure:
        include: "*"
